const { contextBridge, ipcRenderer } = require('electron');
const call = (ch) => (...a) => ipcRenderer.invoke(ch, ...a);
contextBridge.exposeInMainWorld('playou4', {
  list: call('library:list'),
  reveal: call('library:reveal'),
  addFolder: call('folders:add'),
  removeFolder: call('folders:remove'),
  savePlaylist: call('playlists:save'),
  applyAuto: call('playlists:applyAuto'),
  clearAuto: call('playlists:clearAuto'),
  deletePlaylist: call('playlists:delete'),
  addPlay: call('plays:add'),
  move: call('playlist:move'),
  storeInfo: call('store:info'),
  storeReveal: call('store:reveal'),
  storeOpen: call('store:open'),
  storeSaveAs: call('store:saveAs'),
  setSettings: call('settings:set'),
  appInfo: call('app:info'),
  checkUpdate: call('update:check'),
  installUpdate: call('update:install'),
  onUpdate: (cb) => ipcRenderer.on('update:state', (_e, s) => cb(s)),
  showPending: call('show:pending'),
  onShowFile: (cb) => ipcRenderer.on('show:file', (_e, p) => cb(p)),
  onProgress: (cb) => ipcRenderer.on('progress', (_e, p) => cb(p)),
});
